package single

type Step int

const (
	BEFORE_MOVE_USE_STEP Step = iota
	AFTER_MOVE_USE_STEP
	BEFORE_MOVE_DAMAGE_STEP
	AFTER_MOVE_DAMAGE_STEP
	BEFORE_SWITCH_STEP
	AFTER_SWITCH_STEP
	SELF_FAINT_STEP
	OPPONENT_FAINT_STEP
)